version: "3.7"

services:
  mongodb:
    image: mongo:latest
    container_name: mongo #necessary for mongo-express to connect
    volumes: #linking internal storage to the local volume
      - mongodb-data:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express:latest
    ports: #access mongo-express from localhost:8081
      - 8081:8081
    depends_on:
      - mongodb

  express-js:
    build: ./back-express/ #local Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongodb

volumes: #creating a local docker volume for the mongodb data to persist in case of container restart
  mongodb-data: